files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%android_code%/strings.xml
  - source: /app/src/main/res/values/velune_strings.xml
    translation: /app/src/main/res/values-%android_code%/velune_strings.xml
